Resolved TypeError: x is not a contructor
agustina-mazzeo/final-project pull request #25
Opened 2023-05-17 18:13 UTC by agustina-mazzeo

2023-05-17 18:33 UTC, fedecote requested changes

2023-05-17 18:33 UTC, fedecote commented on backend/src/services/rate.read.service.ts
> +        const lastRates = await updateRates(this.rateWriteService);
sorry for not chatching this before. The read service should not depende on any write service. You could move this entire function to the rateWriteService. You could also move the updateRates to the rateswriteservice i think would make more sense to have it there

2023-05-17 18:50 UTC, agustina-mazzeo commented on backend/src/services/rate.read.service.ts
> +        const lastRates = await updateRates(this.rateWriteService);
you are totally right

2023-05-18 14:43 UTC, fedecote approved these changes

2023-05-18 17:12 UTC, merged