Routing, folder and constant fixes
agustina-mazzeo/final-project pull request #9
Opened 2023-04-24 15:29 UTC by agustina-mazzeo

2023-04-24 21:57 UTC, fedecote requested changes

2023-04-24 21:57 UTC, fedecote commented on backend/src/api/routes/transactions.routes.ts
> +    this.router.use('/transactions', authJwt);
replace "/transactions" and "/transfer" with this.path and this.pathTransfer

2023-04-24 21:57 UTC, fedecote commented on backend/src/api/routes/transactions.routes.ts
> +    this.router.use('/transactions', authJwt);
also are you using path, pathTransfer, router, etc from outside this class? If not they should be private

2023-04-24 21:57 UTC, fedecote commented on backend/src/services/accounts.service.ts
> +  public create = async (userId: number): Promise<any> => {
try to avoid using any and define a custom type if needed

2023-04-24 21:57 UTC, fedecote commented on backend/src/utils/helpers.ts
> +export function createToken(user: User): TokenData {
I would move all stuffs related to the api like the token, etc to the api folder. This makes clear that this functions are scoped to just the api.

2023-04-25 12:53 UTC, agustina-mazzeo commented on backend/src/utils/helpers.ts
> +export function createToken(user: User): TokenData {
like an utils subfolder of the api folder?

2023-04-25 17:22 UTC, merged